name = "sentiment-forwarder"
main = "worker/sentiment-forwarder.js"
compatibility_date = "2024-06-28"
workers_dev = true

[vars]
# Where to forward (your intermediate worker or Apps Script web app)
APPS_FORWARD_URL = "https://weathered-disk-a104.distraction.workers.dev/"
ALLOWED_ORIGIN = "https://www.marxia.com"
