name = "sequence-worker"
main = "workers-directory/sequence-worker.js"
compatibility_date = "2024-06-28"
workers_dev = true

[vars]
FORWARDER_BASE = "https://weathered-disk-a104.distraction.workers.dev/"

