name = "marxia-save-lite"
main = "src/index.js"
compatibility_date = "2024-11-20"

[vars]
APP_SCRIPT_URL = "https://script.google.com/macros/s/AKfycb.../exec"

# === Secrets (set with wrangler) ===
# wrangler secret put ASSET_ID
# wrangler secret put KID
# wrangler secret put SIGNING_KEY
