name: Import public repos into monorepo (subtree)

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: monorepo-import
  cancel-in-progress: false

env:
  TARGET_BRANCH: main
  # One per line: <FULL REPO URL>.git : <destination folder in this repo>
  REPOS: |
    https://github.com/fedemenstahgriltrocast-max/ganter-beast.git:apps/ganter-beast
    https://github.com/fedemenstahgriltrocast-max/brasster-boogie.git:apps/brasster-boogie
    https://github.com/fedemenstahgriltrocast-max/glowing-meme.git:apps/glowing-meme
    https://github.com/fedemenstahgriltrocast-max/agents-starter.git:apps/agents-starter
    https://github.com/fedemenstahgriltrocast-max/vllm.git:apps/vllm
    https://github.com/fedemenstahgriltrocast-max/ollama.git:apps/ollama
    https://github.com/fedemenstahgriltrocast-max/LibreChat.git:apps/LibreChat
    https://github.com/fedemenstahgriltrocast-max/github-mcp-server.git:apps/github-mcp-server
    https://github.com/fedemenstahgriltrocast-max/came-llama.git:apps/came-llama
    https://github.com/fedemenstahgriltrocast-max/camello-purple.git:apps/camello-purple
    https://github.com/fedemenstahgriltrocast-max/PurpleLlama.git:apps/PurpleLlama
    https://github.com/fedemenstahgriltrocast-max/murmur.git:apps/murmur
    https://github.com/fedemenstahgriltrocast-max/ollama-ui.git:apps/ollama-ui
    https://github.com/fedemenstahgriltrocast-max/llama-cpp-python.git:apps/llama-cpp-python
    https://github.com/fedemenstahgriltrocast-max/solution-ai-barista.git:apps/solution-ai-barista
    https://github.com/fedemenstahgriltrocast-max/TinyLLM.git:apps/TinyLLM
    https://github.com/fedemenstahgriltrocast-max/LangBot.git:apps/LangBot
    https://github.com/fedemenstahgriltrocast-max/thorium-eter.git:apps/thorium-eter
    https://github.com/fedemenstahgriltrocast-max/TinyLlama.git:apps/TinyLlama
    https://github.com/fedemenstahgriltrocast-max/2checkout-python-sdk.git:apps/2checkout-python-sdk

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout super repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.TARGET_BRANCH }}

      - name: Configure git identity
        run: |
          git config user.name "monorepo-import-bot"
          git config user.email "actions@users.noreply.github.com"

      - name: Import each repo via subtree (public)
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n'
          for line in $REPOS; do
            [ -z "$line" ] && continue
            url="${line%%:*}"
            dest="${line#*:}"

            repo_name="${url##*/}"      # e.g., my-repo.git
            repo_name="${repo_name%.git}"
            alias="src_${repo_name}"

            echo "----"
            echo "Importing ${url} → ${dest}"

            git remote remove "$alias" >/dev/null 2>&1 || true
            git remote add "$alias" "$url"
            git fetch --prune "$alias"

            # Detect default branch (falls back to main)
            default_branch="$(git remote show "$alias" | sed -n 's/.*HEAD branch: //p')"
            if [ -z "$default_branch" ]; then default_branch="main"; fi
            echo "Default branch detected for $repo_name: $default_branch"

            # First time → subtree add; next runs → subtree pull (update)
            if [ -d "$dest" ]; then
              echo "Folder exists → subtree PULL update..."
              git subtree pull --prefix="$dest" "$alias" "$default_branch" -m "Update ${repo_name} into ${dest}"
            else
              echo "Folder not found → subtree ADD import..."
              mkdir -p "$dest"
              git subtree add --prefix="$dest" "$alias" "$default_branch" -m "Import ${repo_name} into ${dest}"
            fi

            git remote remove "$alias" || true
          done

          # Push changes back to this repo
          git push origin "${TARGET_BRANCH}"
