name: Fix submodules and remove llama.cpp vendor

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scrub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main (NO submodules)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          submodules: false

      - name: Configure git identity
        run: |
          git config user.name "submodule-scrub-bot"
          git config user.email "actions@users.noreply.github.com"

      - name: Remove submodule and metadata
        shell: bash
        run: |
          set -euo pipefail
          TARGET="apps/llama-cpp-python/vendor/llama.cpp"

          echo "==> Remove gitlink (if any) and files"
          # If the path is staged as a submodule (mode 160000), remove it from index
          if git ls-files --stage "$TARGET" 2>/dev/null | grep -q '^160000'; then
            git rm -f "$TARGET" || true
          fi
          # Remove any working tree leftovers
          rm -rf "$TARGET"

          echo "==> Clean .gitmodules entries"
          # Remove possible entries under either path variant
          if [ -f .gitmodules ]; then
            git config -f .gitmodules --remove-section "submodule.apps/llama-cpp-python/vendor/llama.cpp" || true
            git config -f .gitmodules --remove-section "submodule.vendor/llama.cpp" || true
            # Also purge any lingering entry whose 'path' matches our TARGET
            for name in $(git config -f .gitmodules --name-only --get-regexp '^submodule\..*\.path$' 2>/dev/null | sed 's/\.path$//'); do
              p=$(git config -f .gitmodules --get "${name}.path" || true)
              if [ "$p" = "$TARGET" ] || [ "$p" = "vendor/llama.cpp" ]; then
                git config -f .gitmodules --remove-section "$name" || true
              fi
            done
            git add .gitmodules || true
          fi

          echo "==> Stage and commit changes (if any)"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: remove apps/llama-cpp-python/vendor/llama.cpp and scrub submodule metadata"
            git push origin main
          else
            echo "No changes to commit."
          fi


